name: wemapgl
description: WeMap Flutter SDK
version: 0.1.0
homepage: https://github.com/WEMAP-Official/WeMap-Flutter-SDK
publish_to: none
dependencies:
  flutter:
    sdk: flutter
    
  fluttertoast: ^3.1.0
  url_launcher: ^5.4.2
  sqflite: ^1.1.6+5
  intl: ^0.16.0
  path_provider: ^1.6.1
  http: ^0.12.0+4
  async: ^2.3.0
  connectivity: ^0.4.8+1
  rubber: ^0.5.0
  syncfusion_flutter_charts: ^18.3.42
  google_fonts: ^0.3.9
  weather_icons: ^2.0.1
  cupertino_icons: ^1.0.2
  snaplist: ^0.1.8
  location: ^2.5.4

  wemapgl_platform_interface:
    path: ./wemapgl_platform_interface
flutter:
  plugin:
    platforms:
      android:
        package: com.wemap.wemapgl
        pluginClass: WeMapMapsPlugin
      ios:
        pluginClass: WeMapMapsPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  # Flutter versions prior to 1.10 did not support the flutter.plugin.platforms map.
  #flutter: ">=1.10.0 <2.0.0"
